// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvncovwjuyhftbufepns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bmNvdndqdXloZnRidWZlcG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTE2ODksImV4cCI6MjA2NTU2NzY4OX0.kO16VVOmSXLIaFOWrGd5VlQJuvF7i-xG0WCe05px19I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);